name: Deploy pi-cture on Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, raspberrypi]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm install

      - name: Restart App with PM2
        run: |
          cd /home/pi/pi-cture
          pm2 restart pi-cture || pm2 start npm --name "pi-cture" -- run start
